### ISSUE TITLE
how to add to an already created venv?

### ISSUE THREAD

**Issue by akhanf** [pvandyken/kslurm#18]
You can `kpy create` a venv on the login node, then install to it and save it, but then if you want to make changes to it in the future there doesn't seem to be an easy way to do this, since the commands to load and activate can only be run on a compute node. Am I missing something? 

Also, would be useful to be able to `kpy list` the venvs on login node too, but this is also disabled for non-compute nodes..

**Comment by pvandyken** [comment]
I can add the ability to `load` modules on a login node; there's a fairly arbitrary check preventing that right now. I suppose the primary use-case is to `pip install` packages that may not be pre-downloaded?

For `list`ing and `activate`ing, this is actually more complicated. All of the envs are being put into the `/tmp` dir, and I don't have a specific, user-owned `/tmp/{user}-kslurm` folder. I don't want to make such a folder on the public `/tmp` dir, as it's impossible to ensure you'll have complete control over the target directory without race conditions without using `tempfile.mkdtemp()`, which inherently includes a random component. So really the only way is to keep a central database of all the envs created and their location. I'm actually already doing this on compute nodes, but I'm putting it on `$SLURM_TMPDIR`. This is super convenient, as the database dies automatically when the compute node dies. For a login node, I'd have to put it under `~/.config` and that adds burden of checking for invalidation etc. So doable, but more complicated.

Is there a specific use case for `list`ing on the login node?

**Comment by akhanf** [comment]
Ah I thought it was just providing a listing based on the .tar files -- I haven't actually used the function yet, but will try now that I have the fix-- but yes was for the general use case of updating venvs on the login node, to know what venvs are there before loading and updating.

**Comment by pvandyken** [comment]
Ah, so `kpy list` lists the currently loaded venvs. If you just want to list what saved venvs are available, you can call `kpy load` without arguments. Currently this will still only work on a login node, but I'll have that fixed soon

**Comment by akhanf** [comment]
ah ok thanks!

**Comment by pvandyken** [comment]
I do think it's confusing though... `kpy list` *sounds like* it should list the tar files. Any thoughts on a better name?

**Comment by pvandyken** [comment]
fyi, this is now fixed on `v0.3.4`, downloadable from pypi
